name: "build"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

env:
  GODOT_VERSION: 4.6
  EXPORT_NAME: Etch
  VERSION: v0.1.0-dev1

jobs:
  windows-export:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${VERSION}_Windows
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: | 
          cd etch
          godot --headless --import
          godot --headless -v --export-release "Windows Desktop" ../build/${EXPORT_NAME}_${VERSION}_Windows/${EXPORT_NAME}_${VERSION}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Etch Windows
          path: build/${{ env.EXPORT_NAME }}_${{ env.VERSION }}_Windows
          retention-days: 14

  linux-export:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${VERSION}_Linux
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: | 
          cd etch
          godot --headless --import
          godot --headless -v --export-release "Linux" ../build/${EXPORT_NAME}_${VERSION}_Linux/${EXPORT_NAME}_${VERSION}.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Etch Linux
          path: build/${{ env.EXPORT_NAME }}_${{ env.VERSION }}_Linux
          retention-days: 14

  mac-export:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${VERSION}_Mac
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: | 
          cd etch
          godot --headless --import
          godot --headless -v --export-release "macOS" ../build/${EXPORT_NAME}_${VERSION}_Mac/${EXPORT_NAME}_${VERSION}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Etch Mac
          path: build/${{ env.EXPORT_NAME }}_${{ env.VERSION }}_Mac
          retention-days: 14